version: '3.8'

services:
  # --- WEB SERVER (Apache) ---
  apache:
    image: httpd:2.4
    container_name: apache-web-server
    ports:
      - "8080:80"
    volumes:
      # Mount folder www/ ke root dokumen Apache
      - ./www:/var/www/html
      # Mount konfigurasi Apache kustom
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/vhosts:/usr/local/apache2/conf/vhosts
    depends_on:
      - php-83-fpm
      - php-74-fpm

  # --- PHP FPM 8.3 ---
  php-83-fpm:
    build:
      context: ./php-83-fpm
    container_name: php-83-fpm
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"

  # --- PHP FPM 7.4 ---
  php-74-fpm:
    build:
      context: ./php-74-fpm
    container_name: php-74-fpm
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"

  # --- DATABASE (MySQL 8.0) ---
  db-mysql:
    image: mysql/mysql-server:8.0
    container_name: db-mysql-80
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
    volumes:
      - mysql_data:/var/lib/mysql

  # --- DATABASE (PostgreSQL 13) ---
  db-postgre:
    image: postgres:13-alpine
    container_name: db-postgre-13
    environment:
      POSTGRES_DB: db_postgre
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data: